name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 8.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 8.15.1
      - name: Print ACCESS_TOKEN
        run: echo "ACCESS_TOKEN is ${{ secrets.ACCESS_TOKEN }}"
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
      - name: Print ACCESS_TOKEN
        run: echo "ACCESS_TOKEN is ${{ secrets.ACCESS_TOKEN }}"
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: master
          FOLDER: dist/ang-website
          BUILD_SCRIPT: npm install && npm run build -- --prod
